export const NEW_BANNER_REQUEST = "NEW_BANNER_REQUEST";
export const NEW_BANNER_SUCCESS = "NEW_BANNER_SUCCESS";
export const NEW_BANNER_RESET = "NEW_BANNER_RESET";
export const NEW_BANNER_FAIL = "NEW_BANNER_FAIL";


export const GET_ALL_BANNERS_REQUEST = 'GET_ALL_BANNERS_REQUEST';
export const GET_ALL_BANNERS_SUCCESS = 'GET_ALL_BANNERS_SUCCESS';
export const GET_ALL_BANNERS_FAIL = 'GET_ALL_BANNERS_FAIL';

export const GET_BANNER_BY_ID_REQUEST = 'GET_BANNER_BY_ID_REQUEST';
export const GET_BANNER_BY_ID_SUCCESS = 'GET_BANNER_BY_ID_SUCCESS';
export const GET_BANNER_BY_ID_FAIL = 'GET_BANNER_BY_ID_FAIL';


export const UPDATE_BANNER_REQUEST = 'UPDATE_BANNER_REQUEST';
export const UPDATE_BANNER_SUCCESS = 'UPDATE_BANNER_SUCCESS';
export const UPDATE_BANNER_RESET = 'UPDATE_BANNER_SUCCESS';
export const UPDATE_BANNER_FAIL = 'UPDATE_BANNER_FAIL';

export const DELETE_BANNER_REQUEST = 'DELETE_BANNER_REQUEST';
export const DELETE_BANNER_SUCCESS = 'DELETE_BANNER_SUCCESS';
export const DELETE_BANNER_RESET = 'DELETE_BANNER_RESET';
export const DELETE_BANNER_FAIL = 'DELETE_BANNER_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

