// Constants for coupon actions
export const COUPON_CREATE_REQUEST = 'COUPON_CREATE_REQUEST';
export const COUPON_CREATE_SUCCESS = 'COUPON_CREATE_SUCCESS';
export const COUPON_CREATE_RESET = 'COUPON_CREATE_RESET';
export const COUPON_CREATE_FAIL = 'COUPON_CREATE_FAIL';

export const COUPON_DELETE_REQUEST = 'COUPON_DELETE_REQUEST';
export const COUPON_DELETE_SUCCESS = 'COUPON_DELETE_SUCCESS';
export const COUPON_DELETE_RESET = 'COUPON_DELETE_RESET';
export const COUPON_DELETE_FAIL = 'COUPON_DELETE_FAIL';

export const COUPON_GET_ALL_REQUEST = 'COUPON_GET_ALL_REQUEST';
export const COUPON_GET_ALL_SUCCESS = 'COUPON_GET_ALL_SUCCESS';
export const COUPON_GET_ALL_FAIL = 'COUPON_GET_ALL_FAIL';


export const APPLY_COUPON_REQUEST = 'APPLY_COUPON_REQUEST';
export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS';
export const APPLY_COUPON_FAILURE = 'APPLY_COUPON_FAILURE';


export const CLEAR_ERRORS = "CLEAR_ERRORS";


